import type { Metadata } from 'next'
import './globals.css'
import Providers from '@/components/Providers/Providers'
import { Inter as FontSans } from "next/font/google"
import Header from '@/components/Header/Header'
 
import { cn } from "@/lib/utils"
import { NextFontWithVariable } from 'next/dist/compiled/@next/font'
 
const fontSans: NextFontWithVariable = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <Providers 
         attribute="class"
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange>
          <Header />
            {children}
        </Providers>
        </body>
    </html>
  )
}
